2025-03-02 02:15:26,997 INFO    MainThread:45335 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-02 02:15:26,997 INFO    MainThread:45335 [wandb_setup.py:_flush():67] Configure stats pid to 45335
2025-03-02 02:15:26,997 INFO    MainThread:45335 [wandb_setup.py:_flush():67] Loading settings from /home/ic41223/.config/wandb/settings
2025-03-02 02:15:26,997 INFO    MainThread:45335 [wandb_setup.py:_flush():67] Loading settings from /home/ic41223/DA6401/wandb/settings
2025-03-02 02:15:26,997 INFO    MainThread:45335 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-02 02:15:26,998 INFO    MainThread:45335 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/ic41223/DA6401/wandb/run-20250302_021526-z1y12tdz/logs/debug.log
2025-03-02 02:15:26,998 INFO    MainThread:45335 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/ic41223/DA6401/wandb/run-20250302_021526-z1y12tdz/logs/debug-internal.log
2025-03-02 02:15:26,998 INFO    MainThread:45335 [wandb_init.py:init():761] calling init triggers
2025-03-02 02:15:26,998 INFO    MainThread:45335 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'wandb_project': 'Assignment1', 'wandb_entity': 'harshayelchuri', 'dataset': 'fashion_mnist', 'epochs': 1, 'batch_size': 4, 'loss': 'cross_entropy', 'optimizer': 'sgd', 'learning_rate': 0.1, 'momentum': 0.5, 'beta': 0.5, 'beta1': 0.5, 'beta2': 0.5, 'epsilon': 1e-06, 'weight_decay': 0.0, 'weight_init': 'random', 'num_layers': 1, 'hidden_size': 4, 'activation': 'sigmoid', '_wandb': {}}
2025-03-02 02:15:26,998 INFO    MainThread:45335 [wandb_init.py:init():784] starting backend
2025-03-02 02:15:26,998 INFO    MainThread:45335 [wandb_init.py:init():788] sending inform_init request
2025-03-02 02:15:27,001 INFO    MainThread:45335 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-03-02 02:15:27,001 INFO    MainThread:45335 [wandb_init.py:init():803] backend started and connected
2025-03-02 02:15:27,004 INFO    MainThread:45335 [wandb_init.py:init():896] updated telemetry
2025-03-02 02:15:27,024 INFO    MainThread:45335 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-03-02 02:15:27,730 ERROR   MainThread:45335 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/ic41223/miniconda3/envs/DA6401/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
  File "/home/ic41223/miniconda3/envs/DA6401/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 968, in init
    raise error
wandb.errors.errors.CommError: failed to upsert bucket: returned error 403 Forbidden: {"errors":[{"message":"permission denied","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}
2025-03-02 02:15:27,739 WARNING MsgRouterThr:45335 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "/home/ic41223/miniconda3/envs/DA6401/lib/python3.9/site-packages/wandb/sdk/interface/router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
  File "/home/ic41223/miniconda3/envs/DA6401/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
  File "/home/ic41223/miniconda3/envs/DA6401/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ic41223/miniconda3/envs/DA6401/lib/python3.9/site-packages/wandb/sdk/interface/router.py", line 70, in message_loop
    msg = self._read_message()
  File "/home/ic41223/miniconda3/envs/DA6401/lib/python3.9/site-packages/wandb/sdk/interface/router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-03-02 02:15:27,740 INFO    MsgRouterThr:45335 [mailbox.py:close():115] Closing mailbox, abandoning 0 handles.
